version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-container
    environment:
      SA_PASSWORD: Informativo123@
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILE_ACTIVE: Prod
    ports:
      - "8080:8080"
    depends_on:
      - sql-server